### ISSUE TITLE
AssertionError: mkbootimg of RECOVERY image failed

### ISSUE THREAD

**Issue by Attached2Android** [CandyRoms/build#1]
--kernel <filename>
       [ --ramdisk <filename> ]
       [ --second <2ndbootloader-filename> ]
       [ --cmdline <kernel-commandline> ]
       [ --board <boardname> ]
       [ --base <address> ]
       [ --pagesize <pagesize> ]
       [ --dt <filename> ]
       [ --kernel_offset <address> ]
       [ --ramdisk_offset <address> ]
       [ --second_offset <address> ]
       [ --tags_offset <address> ]
       [ --id ]
       [ --mtk 1 ]
       -o|--output <filename>
building image from target_files RECOVERY...
Traceback (most recent call last):
  File "./build/tools/releasetools/make_recovery_patch", line 55, in <module>
    main(sys.argv[1:])
  File "./build/tools/releasetools/make_recovery_patch", line 40, in main
    input_dir, "RECOVERY")
  File "/home/rajkumar_smith_rk/candy/build/tools/releasetools/common.py", line 683, in GetBootableImage
    info_dict, has_ramdisk, two_step_image)
  File "/home/rajkumar_smith_rk/candy/build/tools/releasetools/common.py", line 546, in _BuildBootableImage
    os.path.basename(sourcedir),)
AssertionError: mkbootimg of RECOVERY image failed

**Comment by NoSpamDan** [comment]
@Attached2Android Huh?

**Comment by NoSpamDan** [comment]
You need to push a proposed fix to Gerrit.  No indication of what device you are trying to build either?

**Comment by Attached2Android** [comment]
Device - LAVA IRISX8 - MT6592 - 3.4.67 KERNEL 

- CANDY - NOUGAT

**Comment by NoSpamDan** [comment]
Outdated, bud...
